using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using ReflectionIT.ComparisonOperatorsGenerator.Attributes;

namespace ReflectionIT.ComparisonOperatorsGenerator.Test;

public class ComparisonOperatorsGeneratorTests {

    private static string VersionNumber { get; } = typeof(ComparisonOperatorsGeneratorTests).Assembly.GetName().Version!.ToString();

    [Fact]
    public async Task GenerateClass() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                
                {{ATTRIBUTE_CODE_IN_TEST}}

                namespace Demo {

                    [ComparisonOperators]
                    partial class Point(int X, int Y) : IComparable<Point> {

                        public int X = X;
                        public int Y = Y;

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point? other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial class Point
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task GenerateClassInNestedNamespace() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                
                {{ATTRIBUTE_CODE_IN_TEST}}

                namespace Demo.Helpers {

                    [ComparisonOperators]
                    partial class Point(int X, int Y) : IComparable<Point> {

                        public int X = X;
                        public int Y = Y;

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point? other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Helpers.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo.Helpers
            {
                partial class Point
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task GenerateGenericClass() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                                
                {{ATTRIBUTE_CODE_IN_TEST}}

                namespace Demo {

                    [ComparisonOperators]
                    partial class Point<T>(int X, int Y) : IComparable<Point<T>> {

                        public int X = X;
                        public int Y = Y;

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point<T>? other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Point{T}.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial class Point<T>
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point<T> left, Point<T> right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point<T> left, Point<T> right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point<T> left, Point<T> right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point<T> left, Point<T> right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task GenerateClassWithNoNamespace() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                
                {{ATTRIBUTE_CODE_IN_TEST}}

                [ComparisonOperators]
                partial class Point(int X, int Y) : IComparable<Point> {

                    public int X = X;
                    public int Y = Y;

                    public double Dist => Math.Sqrt((X * X) + (Y * Y));

                    public int CompareTo(Point other) {
                        return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                    }
                }
                
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            partial class Point
            {
                [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                /// <summary>Compares two values to determine which is less.</summary>
                /// <param name="left">The value to compare with <paramref name="right" />.</param>
                /// <param name="right">The value to compare with <paramref name="left" />.</param>
                /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                
                [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                /// <summary>Compares two values to determine which is less or equal.</summary>
                /// <param name="left">The value to compare with <paramref name="right" />.</param>
                /// <param name="right">The value to compare with <paramref name="left" />.</param>
                /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                
                [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                /// <summary>Compares two values to determine which is greater.</summary>
                /// <param name="left">The value to compare with <paramref name="right" />.</param>
                /// <param name="right">The value to compare with <paramref name="left" />.</param>
                /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                
                [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                /// <summary>Compares two values to determine which is greater or equal.</summary>
                /// <param name="left">The value to compare with <paramref name="right" />.</param>
                /// <param name="right">The value to compare with <paramref name="left" />.</param>
                /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task GenerateStruct() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                
                {{ATTRIBUTE_CODE_IN_TEST}}
                
                namespace Demo {

                    [ComparisonOperators]
                    readonly partial struct Point(int X, int Y) : IComparable<Point> {

                        public readonly int X = X;
                        public readonly int Y = Y;

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               $"Demo.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial struct Point
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task GenerateRecordClass() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                
                {{ATTRIBUTE_CODE_IN_TEST}}
                
                namespace Demo {

                    [ComparisonOperators]
                    partial record class Point(int X, int Y) : IComparable<Point> {

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial record class Point
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task GenerateRecordStruct() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
               
                {{ATTRIBUTE_CODE_IN_TEST}}
                
                namespace Demo {

                    [ComparisonOperators]
                    readonly partial record struct Point(int X, int Y) : IComparable<Point> {

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial record struct Point
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }

    [Fact]
    public async Task ImplementIComparisonOperatorsInterface() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
               
                {{ATTRIBUTE_CODE_IN_TEST}}
                
                namespace Demo {

                    [ComparisonOperators(ImplementIComparisonOperatorsInterface = true)]
                    readonly partial record struct Point(int X, int Y) : IComparable<Point> {

                        public double Dist => Math.Sqrt((X * X) + (Y * Y));

                        public int CompareTo(Point other) {
                            return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                        }
                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial record struct Point : global::System.Numerics.IComparisonOperators<Point,Point,bool> 
                {
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is less or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                    
                    [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                    [global::System.Diagnostics.DebuggerNonUserCode]
                    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                    /// <summary>Compares two values to determine which is greater or equal.</summary>
                    /// <param name="left">The value to compare with <paramref name="right" />.</param>
                    /// <param name="right">The value to compare with <paramref name="left" />.</param>
                    /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                    public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                }
            }

            """));

        await context.RunAsync();
    }


    [Fact]
    public async Task GenerateNestedClass() {

        var referenceAssemblies = ReferenceAssemblies.Net.Net80.AddAssemblies(
                [typeof(ComparisonOperatorsAttribute).Assembly.Location]
            );

        var context = new CSharpSourceGeneratorTest<SourceGenerator, DefaultVerifier> {
            ReferenceAssemblies = referenceAssemblies,
            CompilerDiagnostics = CompilerDiagnostics.Errors,
            TestCode = $$"""
                using System;
                using System.Collections.Generic;
                
                {{ATTRIBUTE_CODE_IN_TEST}}
                
                namespace Demo {

                    partial class Parent {

                        [ComparisonOperators]
                        partial class Point(int X, int Y) : IComparable<Point> {

                            public int X = X;
                            public int Y = Y;

                            public double Dist => Math.Sqrt((X * X) + (Y * Y));

                            public int CompareTo(Point other) {
                                return Comparer<double>.Default.Compare(this.Dist, other.Dist);
                            }
                        }

                    }
                }
                """
        };

        // List of expected generated sources
        context.TestState.GeneratedSources.Add((typeof(SourceGenerator), $"{SourceGenerator.FullyQualifiedAttributeName}.g.cs", ATTRIBUTE_CODE_CONDITIONAL));

        context.TestState.GeneratedSources.Add((typeof(SourceGenerator),
                                               "Demo.Parent.Point.g.cs", $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGeneratorAttribute source generator
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            #pragma warning disable
            #nullable enable annotations
            
            namespace Demo
            {
                partial class Parent
                {
                    partial class Point
                    {
                        [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                        [global::System.Diagnostics.DebuggerNonUserCode]
                        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                        /// <summary>Compares two values to determine which is less.</summary>
                        /// <param name="left">The value to compare with <paramref name="right" />.</param>
                        /// <param name="right">The value to compare with <paramref name="left" />.</param>
                        /// <returns><c>true</c> if <paramref name="left" /> is less than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                        public static bool operator <(Point left, Point right) => left.CompareTo(right) < 0;
                        
                        [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                        [global::System.Diagnostics.DebuggerNonUserCode]
                        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                        /// <summary>Compares two values to determine which is less or equal.</summary>
                        /// <param name="left">The value to compare with <paramref name="right" />.</param>
                        /// <param name="right">The value to compare with <paramref name="left" />.</param>
                        /// <returns><c>true</c> if <paramref name="left" /> is less than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                        public static bool operator <=(Point left, Point right) => left.CompareTo(right) <= 0;
                        
                        [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                        [global::System.Diagnostics.DebuggerNonUserCode]
                        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                        /// <summary>Compares two values to determine which is greater.</summary>
                        /// <param name="left">The value to compare with <paramref name="right" />.</param>
                        /// <param name="right">The value to compare with <paramref name="left" />.</param>
                        /// <returns><c>true</c> if <paramref name="left" /> is greater than <paramref name="right" />; otherwise, <c>false</c>.</returns>
                        public static bool operator >(Point left, Point right) => left.CompareTo(right) > 0;
                        
                        [global::System.CodeDom.Compiler.GeneratedCode("ReflectionIT.ComparisonOperatorsGeneratorAttribute", "{{VersionNumber}}")]
                        [global::System.Diagnostics.DebuggerNonUserCode]
                        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                        /// <summary>Compares two values to determine which is greater or equal.</summary>
                        /// <param name="left">The value to compare with <paramref name="right" />.</param>
                        /// <param name="right">The value to compare with <paramref name="left" />.</param>
                        /// <returns><c>true</c> if <paramref name="left" /> is greater than or equal to <paramref name="right" />; otherwise, <c>false</c>.</returns>
                        public static bool operator >=(Point left, Point right) => left.CompareTo(right) >= 0;
                    }
                }
            }

            """));

        await context.RunAsync();
    }

    public const string ATTRIBUTE_CODE = """
            namespace ReflectionIT.ComparisonOperatorsGenerator.Attributes {
            
                /// <summary>
                /// An attribute to indicate that comparison operators should be generated for the target class, struct or record
                /// <para>
                /// This only works if the <see cref="System.IComparable{T}"/> interface is implemented
                /// </para>
                /// </summary>
                [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
                internal class ComparisonOperatorsAttribute : Attribute {
            
                    /// <summary>
                    /// Gets or sets a value indicating whether the <see cref="System.Numerics.IComparisonOperators{TSelf,TOther,TResult}" /> interface should be implemented.
                    /// </summary>
                    public bool ImplementIComparisonOperatorsInterface { get; set; }
                }
            }
            """;

    public const string ATTRIBUTE_CODE_CONDITIONAL = $$"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the ReflectionIT.ComparisonOperatorsGenerator source generator
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            #nullable enable
            #if COMPARISON_OPERATORS_GENERATOR_EMBED_ATTRIBUTES
            {{ATTRIBUTE_CODE}}
            #endif
            """;

    public const string ATTRIBUTE_CODE_IN_TEST = $$"""
            using ReflectionIT.ComparisonOperatorsGenerator.Attributes;
            
            {{ATTRIBUTE_CODE}}
            
            """;

}
